name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["**.json", "**.js", "**.ts", "**.jsx", "**.tsx", "**.yml"]
  pull_request:
    branches: [main]
    paths: ["**.json", "**.js", "**.ts", "**.jsx", "**.tsx", "**.yml"]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    env:
      DEBUG: pw:browser*
    steps:
      - name: boost
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -yq libboost-dev
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          # npm install
          npm ci

      - name: Blocked dependency check
        run: npm run security:blocked-deps

      - name: Fix Ubuntu 24.04 issue https://github.com/electron/electron/issues/17972
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          file=node_modules/electron/dist/chrome-sandbox
          sudo chown root $file
          sudo chmod 4755 $file
      - name: Build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run npm test
      - name: Run Playwright tests
        if: startsWith(matrix.os, 'macos')
        run: npm test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 7
